spring.application.name=medicar
# Configuraci\u00f3n de la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medicar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=medicar_usr
spring.datasource.password=1234

# Configuraci\u00f3n de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Desactivar el cach\u00e9 para que los cambios en HTML se vean al instante
spring.thymeleaf.cache=false

# Forzar el reinicio autom\u00e1tico cuando cambien clases Java
spring.devtools.restart.enabled=true

# Habilitar el LiveReload en el navegador
spring.devtools.livereload.enabled=true

# Puerto del servidor
#server.port=8080


# Configuraci\u00f3n de la base de datos MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/nombre_tu_base_datos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=tu_usuario_mysql
#spring.datasource.password=tu_contrase\u00f1a_mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci\u00f3n de JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Puerto del servidor
#server.port=8080